### ISSUE TITLE
Partition 0 could not be fully assigned!

### ISSUE THREAD

**Issue by nitishgoyal13** [SiftScience/kafka-assigner#11]
Exception in thread "main" java.lang.IllegalStateException: Partition 0 could not be fully assigned!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at siftscience.kafka.tools.KafkaAssignmentStrategy.assignOrphans(KafkaAssignmentStrategy.java:183)
	at siftscience.kafka.tools.KafkaAssignmentStrategy.getRackAwareAssignment(KafkaAssignmentStrategy.java:56)
	at siftscience.kafka.tools.KafkaTopicAssigner.generateAssignment(KafkaTopicAssigner.java:70)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.printLeastDisruptiveReassignment(KafkaAssignmentGenerator.java:175)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.runTool(KafkaAssignmentGenerator.java:290)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.main(KafkaAssignmentGenerator.java:302)

**Comment by orimarti** [comment]
Same error here in almost all the situations! :)
