### ISSUE TITLE
Partition X could not be fully assigned!

### ISSUE THREAD

**Issue by s905060** [SiftScience/kafka-assigner#5]
How can we avoid the exception?
```
./kafka-assignment-generator.sh --zk_string XXXXXXXXXX:2181 --mode PRINT_REASSIGNMENT --disable_rack_awareness --broker_hosts_to_remove XXXXXXXXXX
```
```
Exception in thread "main" java.lang.IllegalStateException: Partition 99 could not be fully assigned!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at siftscience.kafka.tools.KafkaAssignmentStrategy.assignOrphans(KafkaAssignmentStrategy.java:183)
	at siftscience.kafka.tools.KafkaAssignmentStrategy.getRackAwareAssignment(KafkaAssignmentStrategy.java:56)
	at siftscience.kafka.tools.KafkaTopicAssigner.generateAssignment(KafkaTopicAssigner.java:70)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.printLeastDisruptiveReassignment(KafkaAssignmentGenerator.java:175)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.runTool(KafkaAssignmentGenerator.java:290)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.main(KafkaAssignmentGenerator.java:302)
```

**Comment by s905060** [comment]
as well as this
```
Exception in thread "main" java.lang.IllegalStateException: Topic XXXXXXXX has partition 18 with unexpected replication factor 4
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at siftscience.kafka.tools.KafkaTopicAssigner.generateAssignment(KafkaTopicAssigner.java:58)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.printLeastDisruptiveReassignment(KafkaAssignmentGenerator.java:175)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.runTool(KafkaAssignmentGenerator.java:290)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.main(KafkaAssignmentGenerator.java:302)
```

**Comment by BrianGallew** [comment]
I'm getting this also.  In my case, it's pretty clearly caused by having partitions with 3 replicas, but only 2 racks.
