### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Partition X could not be fully assigned!

### ISSUE THREAD

**Issue by kaushal1562** [SiftScience/kafka-assigner#7]
Using kafka-assigner-1.1 and getting the below mentioned error. Seems its still not fixed.

./kafka-assignment-generator.sh --zk_string zk-node:port --disable_rack_awareness --topics topic-name  --mode PRINT_REASSIGNMENT

Exception in thread "main" java.lang.IllegalStateException: Partition 18 could not be fully assigned!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at siftscience.kafka.tools.KafkaAssignmentStrategy.assignOrphans(KafkaAssignmentStrategy.java:183)
	at siftscience.kafka.tools.KafkaAssignmentStrategy.getRackAwareAssignment(KafkaAssignmentStrategy.java:56)
	at siftscience.kafka.tools.KafkaTopicAssigner.generateAssignment(KafkaTopicAssigner.java:70)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.printLeastDisruptiveReassignment(KafkaAssignmentGenerator.java:175)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.runTool(KafkaAssignmentGenerator.java:290)
	at siftscience.kafka.tools.KafkaAssignmentGenerator.main(KafkaAssignmentGenerator.java:302)

**Comment by frenchfrywpepper** [comment]
I'm running into this also. Using kafka-assigner-1.1 and --disable_rack_awareness argument. Have you discovered any workarounds?
